import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AppCarousel from "src/components/AppCarousel";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" fixed z-[-1] w-full">
          <AppCarousel />
        </div>
      </main>
    </div>
  );
};

export default Home;
