import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AboutSection from "src/components/Views/AboutSection";
import AppCarousel from "src/components/Views/AppCarousel";
import BestRooms from "src/components/Views/BestRooms";
import SpecialRooms from "src/components/Views/SpecialRooms";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppCarousel />
        <AboutSection />
        <SpecialRooms />
        <BestRooms />
      </main>
    </div>
  );
};

export default Home;
